# One-click publish desktop shell auto-updates (Windows)
#   1. Validate signing private key (.tauri/updater.key, generated by just keygen)
#   2. Signed NSIS build (cargo tauri build --bundles nsis --ci, produces setup.exe + .sig)
#   3. Generate latest.json and publish to GitHub Releases (scripts/publish-update.mjs, needs gh or GITHUB_TOKEN)
#   4. Create local git tag v<version> and push to GitHub / Gitee
# Usage:
#   powershell -File scripts/release-publish.ps1                 # build + publish
#   powershell -File scripts/release-publish.ps1 -BuildOnly      # build only, no publish
#   powershell -File scripts/release-publish.ps1 -Notes "release notes"
param(
  [string]$Notes = "auto update release",
  [switch]$BuildOnly
)
$ErrorActionPreference = 'Stop'

$root = Split-Path -Parent $PSScriptRoot          # repository root
$keyPath = Join-Path $root '.tauri\updater.key'
$manifest = Join-Path $root 'scripts\publish-update.mjs'

# ---- 0. Validate key ----
if (!(Test-Path $keyPath)) {
  Write-Host "[release-publish] signing private key not found: $keyPath" -ForegroundColor Red
  Write-Host "[release-publish] please run: just keygen" -ForegroundColor Yellow
  exit 1
}

# ---- 1. Signed build (--ci skips key password prompt; TAURI_SIGNING_PRIVATE_KEY can be a key file path) ----
$env:TAURI_SIGNING_PRIVATE_KEY = $keyPath
Write-Host "[release-publish] signed build started (NSIS, --ci)..." -ForegroundColor Cyan
Push-Location (Join-Path $root 'src-tauri')
cargo tauri build --target x86_64-pc-windows-msvc --bundles nsis --ci
$buildExit = $LASTEXITCODE
Pop-Location
if ($buildExit -ne 0) { Write-Host "[release-publish] build failed (exit $buildExit)" -ForegroundColor Red; exit $buildExit }
Write-Host "[release-publish] build complete: src-tauri\target\x86_64-pc-windows-msvc\release\bundle\nsis\*.exe + .sig" -ForegroundColor Green

if ($BuildOnly) {
  Write-Host "[release-publish] -BuildOnly: skipping publish." -ForegroundColor Yellow
  exit 0
}

# ---- 2. Publish to GitHub Releases ----
Write-Host "[release-publish] publishing (needs gh CLI or GITHUB_TOKEN)..." -ForegroundColor Cyan
node $manifest --notes $Notes
if ($LASTEXITCODE -ne 0) { Write-Host "[release-publish] publish failed (exit $LASTEXITCODE)" -ForegroundColor Red; exit $LASTEXITCODE }

# ---- 3. Create local tag and push to both remotes ----
$version = (Select-String -Path (Join-Path $root 'src-tauri\Cargo.toml') -Pattern '^version = "([^"]+)"').Matches[0].Groups[1].Value
$tag = "v$version"
if (-not (git -C $root tag -l $tag)) { git -C $root tag $tag }
git -C $root push github $tag
git -C $root push origin $tag

Write-Host "[release-publish] publish completed OK" -ForegroundColor Green
Write-Host "  Release: https://github.com/EternalNight996/dsh-desktop/releases/tag/$tag"
Write-Host "  Manifest: https://github.com/EternalNight996/dsh-desktop/releases/latest/download/latest.json"
Write-Host "  sync gitee branch docs if needed:" -ForegroundColor Yellow
Write-Host "    git checkout gitee && git merge master --no-edit && git push origin gitee && git checkout master"
